### ISSUE TITLE
BLAST Database error: No alias or index file found for protein database

### ISSUE THREAD

**Issue by sulfierry** [ncbi/blast-cloud#15]
I have the error below:

Bio.Application.ApplicationError: Non-zero return code 2 from ‘psiblast -out 7NDB_B_WT.out -query 7NDB_B_WT.fasta -db /mnt/research/common-data/Bio/blastdb/nr -evalue 5000 -num_iterations 3 -out_ascii_pssm 7NDB_B_WT.pssm’, message ‘BLAST Database error: No alias or index file found for protein database [/mnt/research/common-data/Bio/blastdb/nr] in search path [/media/leon//Machine_learning_model_binding_free_energy_BFE_change_predictions/TopNetmAb/7NDB/features/7NDB_B_A_344_S::]’

I downloaded the “nr” file from the blast database and created a database link in the directory [/mnt/research/common-data/Bio/blastdb/nr]. But the error persists.

Please, can anyone help me?

**Comment by tom6931** [comment]
Hello,
   Could you post the result of the command below?  BLAST does not seem to think the files are present, so I'd like to see what is in the directory.  It should be a relatively large number of files with extensions like psq, pin, phr, pal etc.

thanks,

Tom

ls -l /mnt/research/common-data/Bio/blastdb/nr

**Comment by sulfierry** [comment]
Hi Tom, thanks for the feedback
![tom](https://user-images.githubusercontent.com/22729945/146599480-fe484205-6ee5-4783-80e6-b74de736cbb1.png)
.

**Comment by tom6931** [comment]
Is there an nr.pal file in the directory?  This is an alias file that ties together all the volumes, and I assume that BLAST is looking for that.

**Comment by sulfierry** [comment]
Earlier I accidentally deleted all the files I unzipped from file nr.    :sweat: 

Now I'm extracting these files again, I believe it will take a few more hours until everything is extracted.

Once this extraction is finished I will check if this "nr.pal" file is in the directory (so far it is not). As soon as I check this procedure I will answer you here.

Thank you again Tom.

**Comment by poeiradonorte** [comment]
Yes there is a file "nr.pal", 
But the error persists
![Screenshot from 2021-12-18 07-55-27](https://user-images.githubusercontent.com/22729945/146638621-e97b1e83-f540-4e51-97ab-5e98a7720d00.png)
.

**Comment by sulfierry** [comment]
![Screenshot from 2021-12-18 07-55-27](https://user-images.githubusercontent.com/22729945/146638705-4e6c24b3-5284-4376-8b78-620a7d3e5487.png)

**Comment by sulfierry** [comment]
It worked out!
The problem was in the way I decompressed  the nr file.
Previously I used the following command:
$ formatdb -i nr.fa -p T

Now I used:
$ makeblastdb -in nr.fa -dbtype prot -out nr

Problem solved, thanks.
